name: lobby
version: '1.0'
main: online.lxbs.minecraft.plugins.lobby.Lobby
api-version: '1.20'
commands:
  menu:
    description: Open the main menu
    usage: /menu
    aliases: ["main"]
  stats:
    description: Open player statistics
    usage: /stats
    aliases: ["statistics"]